---
version: '2.0'
services:

  shush_decrypt:
    build:
     context: ./shush
     dockerfile: Dockerfile
    volumes:
      - "$HOME/.aws:/root/.aws"
    environment:
      AWS_DEFAULT_REGION: us-west-2

  stackup:
    image: realestate/stackup:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /app
    environment:
      AWS_REGION: us-west-2
